# 网站标题
title: "guchizi"

# 网站描述
description: "摄影与随笔"

# 你的域名
url: "https://guchizi.ccwu.cc"

# 根目录（留空）
baseurl: ""

# 使用的主题
remote_theme: mmistakes/minimal-mistakes

# 必须开启的插件
plugins:
  - jekyll-include-cache

# ==============================================
# 下面这段是：Memos 碎碎念功能专用配置
# 作用：让 GitHub Pages 识别 _memos 文件夹里的内容
# ==============================================
collections:
  memos:
    output: true    # 开启 memos 功能（必须开启）
