title: "guchizi"
description: "另一种赛博永生"
url: "https://guchizi.ccwu.cc"
baseurl: ""
locale: "zh-CN"

# 锁定新版 + 强制Neon皮肤
remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: neon

# 关键：强制忽略系统，固定深色
dark_mode_auto: false
force_dark_mode: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

collections:
  memos:
    output: true
    permalink: /:collection/:path/

header:
  nav:
    - title: "随笔日志 / Blog"
      url: /posts/
    - title: "摄影影集 / Gallery"
      url: /gallery/
    - title: "碎碎念 / Memos"
      url: /memos/
